name:                vsat
version:             0.1.0.0
github:              "doyougnu/vsat"
license:             BSD3
author:              "Jeffrey Young"
maintainer:          "youngjef@oregonstate.edu"
copyright:           "2018 Jeffrey Young"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at https://github.com/doyougnu/VSat

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5
- unordered-containers
- hashable
- mtl
# - bifunctors
- deepseq
- genifunctors >= 0.4
# sbv forces us to use LTS-11.22 ghc 8.2.2
- sbv >= 7.12
- cassava
- bytestring
- text
- vector
- time
- tasty-quickcheck
- aeson-pretty
- aeson
- Spock
- wai-extra
- heaps
- megaparsec >= 6.4
# - parser-combinators >= 1.0

library:
  source-dirs: src

default-extensions:
  - NamedFieldPuns
  - OverloadedStrings
  - FlexibleContexts
  - DeriveFunctor
  - DeriveGeneric
  - BangPatterns
  - GeneralizedNewtypeDeriving
  - DeriveTraversable
  - FlexibleInstances
  - DeriveDataTypeable
  - MultiParamTypeClasses
  - RecordWildCards
  - TemplateHaskell

executables:
  vsat:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-orphans
    dependencies:
    - vsat

benchmarks:
  vsat-bench:
    main:                Baselines.hs
    source-dirs:
      - bench
      - src
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  auto:
    main:                Main.hs
    source-dirs:
      - bench/AutoBench
      - src
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  vsat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vsat
    - QuickCheck
    - tasty
    - tasty-hunit
    - tasty-hspec
    - tasty-smallcheck
    - tasty-quickcheck
    - tasty-hspec
