flags: {}
packages:
# system-ghc: false
extra-deps: [genifunctors-0.4]

## uncomment the following lines to tell stack you are in a nix environment
nix:
  enable: true
  pure: false
  packages: [ z3, pkgconfig, zlib ]

resolver: lts-11.22
build:
  library-profiling: false
  executable-profiling: false

# allow-newer: true

# docker:
#   enable: true

# image:
#   containers:
#     - name: vsat
#       base: fpco/stack-run
#       entrypoints:
#         - vsat
