flags: {}
packages:
  - '.'
system-ghc: true
extra-deps:
  - genifunctors-0.4


# ## uncomment the following lines to tell stack you are in a nix environment
nix:
  enable: true
  pure: true
  packages: [ z3, pkgconfig, zlib, abc-verifier, cvc4, yices, boolector]

resolver: lts-16.31

build:
  library-profiling: false
  executable-profiling: false


# allow-newer: true

# docker:
#   enable: true

# image:
#   containers:
#     - name: vsat
#       base: fpco/stack-run
#       entrypoints:
#         - vsat
