flags: {}
packages:
  - '.'
  # - /home/doyougnu/Research/VSat/haskell/lib/sbv
# system-ghc: false
extra-deps:
  - genifunctors-0.4
  - sbv-8.6

  # spock dependencies
  # - Spock-0.13.0.0
  # - Spock-core-0.13.0.0
  # - reroute-0.5.0.0
  # - stm-hamt-1.2.0.2
  # - primitive-extras-0.7.1
  # - deferred-folds-0.9.10.1@sha256:eb2634488e2a836da7d5aed9afd15ad2bead38817249f60bb68e459cc32fb0b0,2928
  # - focus-0.1.5.2@sha256:fc5c76a5be3a9a1c456106d6f389939299c7e05a1a24938b909f043e36a3e37b,1519
  # - primitive-0.6.4.0@sha256:5b6a2c3cc70a35aabd4565fcb9bb1dd78fe2814a36e62428a9a1aae8c32441a1,2079
  # - stm-containers-0.2.16@sha256:e98efa8dcf0045ea8a78a04b4e2763cf2d8bc33aad0750e2f30a67f8f4e933b1,8454


## uncomment the following lines to tell stack you are in a nix environment
nix:
  enable: true
  pure: true
  # packages: [ z3, pkgconfig, zlib, abc-verifier, cvc4, yices, boolector, haskellPackages.hoogle haskellPackages.hasktags]
  packages: [ z3, pkgconfig, zlib ]

# resolver: lts-11.22
# resolver: lts-12.25
# resolver: lts-13.10
resolver: lts-15.3

build:
  library-profiling: false
  executable-profiling: false

# extra-lib-dirs:
#   - /home/doyougnu/Research/VSat/haskell/lib/


# allow-newer: true

# docker:
#   enable: true

# image:
#   containers:
#     - name: vsat
#       base: fpco/stack-run
#       entrypoints:
#         - vsat
