flags: {}
packages:
  - '.'
  # - /home/doyougnu/Research/VSat/haskell/lib/sbv
# system-ghc: false
extra-deps:
  - genifunctors-0.4
  - sbv-8.3
  # spock dependencies
  # - Spock-0.13.0.0
  # - Spock-core-0.13.0.0
  # - reroute-0.5.0.0
  # - stm-containers-1.1.0.2
  # - stm-hamt-1.2.0.2
  # - primitive-extras-0.7.1

## uncomment the following lines to tell stack you are in a nix environment
nix:
  enable: true
  pure: false
  packages: [ z3, pkgconfig, zlib, abc-verifier, cvc4, yices, boolector ]

# resolver: lts-11.22
resolver: lts-12.25
# resolver: lts-13.10

build:
  library-profiling: false
  executable-profiling: false

# extra-lib-dirs:
#   - /home/doyougnu/Research/VSat/haskell/lib/


# allow-newer: true

# docker:
#   enable: true

# image:
#   containers:
#     - name: vsat
#       base: fpco/stack-run
#       entrypoints:
#         - vsat
