flags: {}
packages:
  - '.'
  - /home/doyougnu/Research/VSat/haskell/lib/sbv
# system-ghc: false
extra-deps:
  - genifunctors-0.4

## uncomment the following lines to tell stack you are in a nix environment
nix:
  enable: true
  pure: false
  packages: [ z3, pkgconfig, zlib ]

# resolver: lts-11.22
resolver: lts-12.25
# resolver: lts-13.0 -- for deriving via

build:
  library-profiling: true
  executable-profiling: true

extra-lib-dirs:
  - /home/doyougnu/Research/VSat/haskell/lib/


# allow-newer: true

# docker:
#   enable: true

# image:
#   containers:
#     - name: vsat
#       base: fpco/stack-run
#       entrypoints:
#         - vsat
